on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up JDK 11.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'

      - name: Build, run unit and component tests
        run: ./mvnw clean verify -pl '!e2e'

      - name: Check docker images
        run: docker images

      - name: Setup kind and create cluster
        uses: rockyhmchen/gh-actions-kind-env@js-ver
        with:
          kind-version: "v0.5.1"

      - name: Load docker image
        run: |
          scripts/2_load_docker_images.sh

      - name: Create an integration test environment
        run: |
          scripts/3_set_image.sh
          scripts/4_startup.sh

      - name: Setup kubefwd
        uses: rockyhmchen/gh-actions-setup-kubefwd@master
        with:
          kubefwd-version: "v1.9.2"

      - name: Port-forward
        #        run: sudo -u root scripts/5_kubefwd_kind.sh /opt/hostedtoolcache/kubefwd/1.9.2/x64/kubefwd &
        run: sudo -u root /opt/hostedtoolcache/kubefwd/1.9.2/x64/kubefwd svc -n itest &

      - name: Run integration tests
        run: ./mvnw clean verify -pl 'e2e'

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          TAG=$(echo ${GITHUB_REF} | cut -d'/' -f3)
          docker login docker.pkg.github.com --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
          docker tag com.rc/magnesium:DEV docker.pkg.github.com/${GITHUB_REPOSITORY}/magnesium:$TAG
          docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/magnesium:$TAG